local=/mydomain.local/
domain=mydomain.local
mx-host=mydomain.local,mail.mydomain.local,10
txt-record=mydomain.local,"v=spf1 mx -all"
txt-record=_dmarc.mydomain.local,"v=DMARC1; p=reject; rua=mailto:admin@mydomain.local; ruf=mailto:admin@mydomain.local"
txt-record=202604e._domainkey.mydomain.local,"v=DKIM1; k=ed25519; h=sha256; p=h6IPZhiczymeNWGazf0/YfACD3Rys7D0kLCGHF0Zuscc="
txt-record=202604r._domainkey.mydomain.local,"v=DKIM1; k=rsa; h=sha256; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtlDKMtcsJX/GXBmdsMvTsT9FU7Jsi+ZJFsiSx7ozt48P5cI+obn/UdQNSCgt03zqfbEPRAE6hcQYzscEWI3Q8HTTq4zscvPpb4VpNrwvbqkHXZDsBE4vgvZNS8M+lnP0xP4qv0Dn53HXwQuZi4lvlRwa2Serf2pKJ7zL2QqhEpW9S8T+W4/6Y5fcDpVkUVfo8fHqtQl2AM5TATo4uDdfWTuCJRJM5I+YUbn40xKs2gs2qYpu+5GJLFgOA3iQS5oCfA06aX+7T7U82QgtoT2wrk0ZbW73NTjiIPpvwO5e6ozBtzsqpOwxQN1viK0cTI9WX7UdctVDfbfPQpIlLoGRYQIDAQAB"
